#pragma once

#include "hal/hal_data_types.h"

#define EVENT_CONNECTION_REQUIRED (1 << 0)
#define EVENT_SOFTWARE_UPGRADE_REQUIRED (1 << 1)
#define EVENT_BLE_CONNECTION (1 << 2)

#define DATA_UPLOAD_ERROR_TCP_CONNETION_FAILED 1
#define DATA_UPLOAD_ERROR_BLE_DISCONNCTED 2
#define DATA_UPLOAD_ERROR_FLASH 3
#define DATA_UPLOAD_ERROR_TCP_SENDING_FAILED 4
#define DATA_UPLOAD_ERROR_ABORTED_BY_APP 5
#define DATA_UPLOAD_ERROR_DISCONNECTION_MSG 6
#define DATA_UPLOAD_ERROR_CONNECTION_TIMEOUT 7

#define EVENT_BLE_TRANSFER_SUCCESS (1 << 0)
#define EVENT_BLE_TRANSFER_ERROR (1 << 1)
#define EVENT_BLE_TRANSFER_ABORT (1 << 2)
#define EVENT_BLE_BLOCK_CONFIRM_AND_EXIT (1 << 3)

void transfer_task(void *pvParameter);